version: '3.5'
services:
  api1: &api
    # API - Instância 01
    #    image: api
    build: 
      dockerfile: ./docker/api.Dockerfile
      context: ./
    hostname: api01
    network_mode: 'host'
    depends_on:
      - intermediary_api
    expose:
      - "80"
    env_file: ./env
    environment:
      - RUST_ENV=prod
      - RUST_LOG=info
      - RINHA_URL=http://localhost:50051
      - TARGET_NAME=rinha
      - LOGGER_OUTPUT=stdout
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'
  api2:
    # API - Instancia 02
    <<: *api
    hostname: api02
    environment:
      - RUST_ENV=prod
      - RUST_LOG=info
      - RINHA_URL=http://localhost:50051
      - SERVER_PORT=81
      - TARGET_NAME=rinha
      - LOGGER_OUTPUT=stdout
  nginx:
    # Load Balancer
    image: nginx:latest
    network_mode: 'host'
    volumes:
      - ./nginx.host-network.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'
  intermediary_api:
    build: 
      dockerfile: ./docker/intermediary_api.Dockerfile
      context: ./
    hostname: intermediary_api
    network_mode: 'host'
    ports:
      - 50051:50051
    expose:
      - "50051"
    depends_on:
      - db
    env_file: ./env
    environment:
      - RUST_ENV=prod
      - RUST_LOG=info
      - TARGET_NAME=intermediary_api
      - MAX_BATCH_INSERT_SIZE=2048
      - BATCH_INSERT_INTERVAL_SECS=1
      - DB_HOST=localhost
      - LOGGER_OUTPUT=stdout
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  db:
    # Banco de dados
    image: postgres:15.4-alpine3.18
    network_mode: 'host'
    hostname: db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: rinha_de_backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.0GB'
# networks:
#   default:
#     driver: bridge
#     name: rinha
