[package]
name = "rinha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.7", features = [ "runtime-tokio", "postgres"] }
actix-web = "4"
tracing-subscriber = "0.3.17"
tracing = "0.1.37"
tracing-actix-web = "0.7.6"
actix-cors = "0.6.4"
dotenv = "0.15.0"
serde = "1.0.188"
serde_json = "1.0.105"
chrono = "0.4.26"
uuid = { version = "1.4.1", features = ["v4", "fast-rng", "serde"] }
deadqueue = { version = "0.2.4", features = ["unlimited"] }
tokio = { version = "1.32.0", features = ["full"] }
redis = { version = "0.23.2", features = ["r2d2"] }
deadpool-redis = "0.12.0"

